
#!/bin/bash
tar --use-compress-program=pigz \
-cvpf backup.tar \
/home/z/.ansible \
/home/z/.bash_history \
/home/z/.bash_logout \
/home/z/.bash_profile \
/home/z/.bashrc \
/home/z/.cache \
/home/z/.CLion2017.3 \
/home/z/.config \
/home/z/.dbus \
/home/z/.delete \
/home/z/Desktop \
/home/z/.dir_colors \
/home/z/.dmenurc \
/home/z/.dmrc \
/home/z/Documents \
/home/z/Downloads \
/home/z/.elinks \
/home/z/.ew.json \
/home/z/.extend.bashrc \
/home/z/.extend.xinitrc \
/home/z/.extend.Xresources \
/home/z/.FBReader \
/home/z/.ff-theme-util_1strun \
/home/z/.fonts \
/home/z/.gimp-2.8 \
/home/z/.gitconfig \
/home/z/gits \
/home/z/.gksu.lock \
/home/z/.gnome \
/home/z/.gtkrc-2.0 \
/home/z/.i3 \
/home/z/.icons \
/home/z/.IntelliJIdea2017.3 \
/home/z/.ipython \
/home/z/.java \
/home/z/.keras \
/home/z/.kingsoft \
/home/z/.klei \
/home/z/.lesshst \
/home/z/.local \
/home/z/MEGA \
/home/z/.moc \
/home/z/.moonchild \
/home/z/productions \
/home/z/.mozilla \
/home/z/.mpd \
/home/z/.mpdconf \
/home/z/Music \
/home/z/.node-gyp \
/home/z/node_modules \
/home/z/.npm \
/home/z/.nv \
/home/z/.nvidia-settings-rc \
/home/z/.oh-my-zsh \
/home/z/Pictures \
/home/z/.pki \
/home/z/.profile \
/home/z/Public \
/home/z/.pulse-cookie \
/home/z/.PyCharmCE2017.3 \
/home/z/.python_history \
/home/z/.sogouinput \
/home/z/.ssh \
/home/z/.steam \
/home/z/Steam \
/home/z/.steampath \
/home/z/.steampid \
/home/z/Templates \
/home/z/.thumbnails \
/home/z/tmp \
/home/z/tools \
/home/z/.urxvt \
/home/z/Videos \
/home/z/.vim \
/home/z/.viminfo \
/home/z/.vimrc \
/home/z/.vscode \
/home/z/.w3m \
/home/z/.wget-hsts \
/home/z/.Xauthority \
/home/z/.Xclients \
/home/z/.Xdefaults \
/home/z/.Xdefaults.bak \
/home/z/.xinitrc \
/home/z/.xprofile \
/home/z/.Xresources \
/home/z/.xsession \
/home/z/.xsession-errors \
/home/z/.xsession-errors.old \
/home/z/.ycm_extra_conf.py \
/home/z/.zcompdump \
/home/z/.zcompdump-z-pc-5.4.2 \
/home/z/.zhistory \
/home/z/.zshrc \
/home/z/.zshrc.bak \
/home/z/.zsh-update \
